@startuml case03
skinparam sequenceMessageAlign center

actor Cliente
participant "Front-end\nLogin" as FE
participant Sistema
participant "Serviço 2FA" as MFA

Cliente -> FE: Envia CPF e senha  
activate FE

FE -> Sistema: Valida credenciais
activate Sistema

alt credenciais válidas
    Sistema --> FE: Retorna OK
    deactivate Sistema

    FE --> Cliente: Solicita segundo fator (se habilitado)
    deactivate FE

    Cliente -> FE: Seleciona método de 2FA
    activate FE

    FE -> MFA: Solicita OTP/biometria
    activate Sistema
    activate MFA

    MFA --> Cliente: Envia OTP / solicita biometria
    deactivate MFA

    Cliente -> FE: Informa OTP / faz biometria
    FE -> MFA: Valida fator
    activate MFA

    alt fator válido
        MFA --> FE: Confirma autenticação
        FE --> Cliente: Acesso liberado

    else fator inválido
        MFA --> FE: Retorna erro
        deactivate MFA

        FE --> Cliente: Permite nova tentativa
    end
else credenciais inválidas
    Sistema --> FE: Retorna erro
    deactivate Sistema
    
    FE --> Cliente: Exibe mensagem de erro e conta pode ser bloqueada
    deactivate FE
end
@enduml