@startuml case02
skinparam sequenceMessageAlign center
actor Cliente
participant FE as "Front-end\nEncerrar Conta"
participant Sistema

Cliente -> FE: Seleciona "Encerrar Conta"
activate FE

FE -> Sistema: Solicita verificação de pendências
activate Sistema

alt sem pendências
    Sistema --> FE: Retorna OK
    FE --> Cliente: Exibe termo de encerramento
    Cliente -> FE: Confirma encerramento
    FE -> Sistema: Confirma encerramento e revoga acesso
    Sistema --> Cliente: Envia protocolo por e-mail
else com pendências
    Sistema --> FE: Retorna lista de pendências
    deactivate Sistema

    FE --> Cliente: Exibe pendências e orientações
    deactivate FE
end
@enduml