@startuml Activity_RegistrarDispositivo
start
:Cliente acessa segurança;
:Seleciona "Registrar dispositivo";
:Preenche dados do novo dispositivo;
if (Dispositivo válido?) then (sim)
  :DeviceService registra dispositivo no DB;
  :App exibe sucesso;
else (não)
  :App exibe erro de verificação;
endif
stop
@enduml