@startuml case11
start
:Cliente seleciona "Solicitar cartão";
:Cliente escolhe cartão físico ou virtual;
:Verifica elegibilidade;
if (Aprovado?) then (sim)
  if (Cartão virtual?) then (sim)
    :Gera cartão virtual (12 meses);
  else (não)
    :Solicita envio físico pelos correios;
  endif
  stop
else (não)
  :Informa negação e motivo;
  stop
endif
@enduml