@startuml OTP
start
:Cliente recebe OTP (SMS/App/E-mail);

repeat
  :Cliente insere código ou usa biometria;
  if (Fator válido) then (sim)
    :Autenticação bem-sucedida;
    stop
  else (não)
    if (tentativas < 3) then (sim)
      :Solicita novo OTP;
    else (não)
      :Bloqueio temporário;
      stop
    endif
  endif
repeat while (Fator inválido)
@enduml