@startuml PIX
start
:Cliente seleciona "PIX" > "Nova Transferência";
:Cliente informa chave e valor;
:Verifica perfil e limites;
if (Limites ok?) then (sim)
  :Solicita confirmação 2FA;
  if (2FA aprovado?) then (sim)
    :Cliente confirma operação;
    :Envia instrução ao BACEN;
    :Exibe comprovante;
    stop
  else (não)
    :Informa bloqueio;
    stop
  endif
else (não)
  :Informa bloqueio;
  stop
endif
@enduml