@startuml case08
skinparam sequenceMessageAlign center

actor Cliente
participant FE as "Front-end\nRealizar Transferência/PIX"
participant Sistema
participant MFA as "Serviço 2FA"
participant PSP as "PSP PIX"

Cliente -> FE: Seleciona "PIX" > "Nova Transferência" 
activate FE

FE --> Cliente: Solicita chave e valor 
deactivate FE

Cliente -> FE: Informa chave e valor 
activate FE

FE -> Sistema: Verifica perfil e limites  
activate Sistema

alt limites OK
    Sistema --> FE: retorna OK
    FE --> Cliente: Solicita 2FA
    Cliente -> FE: Fornece OTP/biometria
    FE -> MFA: Valida credencial
    activate MFA

    MFA --> FE: Confirma credencial
    deactivate MFA

    FE -> PSP: Envia instrução PIX
    activate PSP

    PSP --> Sistema: Confirma retorno
    deactivate PSP

    Sistema --> FE: Atualiza histórico
    FE --> Cliente: Exibe comprovante
else limites excedidos
    Sistema --> FE: Erro de limite
    deactivate Sistema

    FE --> Cliente: Exibe mensagem
    deactivate FE
end
@enduml