@startuml Historico_Atend
skinparam sequenceMessageAlign center

actor Usuário
participant FE as "Front-end\nHistórico de Suporte"
participant Sistema

Usuário -> FE: Seleciona "Histórico de Suporte"
activate FE

FE -> Sistema: Solicita registros de suporte  
activate Sistema

Sistema --> FE: Retorna conversas (chatbot/atendente)  
deactivate Sistema

FE --> Usuário: Exibe histórico com filtros
deactivate FE
@enduml