@startuml Historico_Compras
skinparam sequenceMessageAlign center

actor Cliente
participant FE as "Front-end\nHistórico de Compras"
participant Sistema

Cliente -> FE: Acessa "Histórico de Compras" 
activate FE

FE -> Sistema: Solicita transações de compras  
activate Sistema

Sistema --> FE: Retorna lista de compras  
deactivate Sistema

FE --> Cliente: Exibe histórico com filtros
deactivate FE
deactivate Sistema

@enduml