@startuml case04
start
:Cliente seleciona "Enviar Documentos";

repeat
  :Cliente anexa arquivos;
  :Valida tipo e tamanho;
  if (Documentos válidos) then (sim)
    :Armazena documentos;
    :Confirma recebimento;
    stop
  else
    :Rejeita e solicita novo envio;
  endif
repeat while (Documentos inválidos)
@enduml