@startuml case18
start
:Evento de sistema ocorre;
:Gera notificação;

switch (Canal de opção)
case (SMS)
    :Notificar via SMS;
case (Push)
    :Notificar via Push;
case (E-mail)
    :Notificar via E-mail;
endswitch

:Registra comunicação durante 5 anos;
stop
@enduml